server:
  port: 8080

spring:

  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5KB
      max-file-size: 5MB
      max-request-size: 10MB

  service:
    store:
      uri: http://localhost:8081/store-s3