server:
  port: 8080

spring:

  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      enabled: true
      fileSizeThreshold: 5MB
      maxFileSize: 10MB
      maxRequestSize: 10MB

  service:
    store:
      uri: http://localhost:8081/file/store-s3